/*
 * error_codes.h
 *
 *  Created on: Oct 19, 2014
 *      Author: Max Zhao
 */

#ifndef ERROR_CODES_H_
#define ERROR_CODES_H_

#define ERROR_CODE_UNKNOWN_ERROR 0
#define ERROR_CODE_DEBUG_UART_FAILED 90
#define ERROR_CODE_DEBUG_UART_FAILED_SEND 91
#define ERROR_CODE_DEBUG_UART_NOT_READY_FOR_CRITICAL 92
#define ERROR_CODE_DEBUG_UART_FAILED_SEND_CRITICAL 93
#define ERROR_CODE_USB_NOT_INITIALIZED 94
#define ERROR_CODE_STACK_OVERFLOW 10
#define ERROR_CODE_MALLOC_FAILURE 11
#define ERROR_CODE_MAIN_SCHEDULER_FALL_THRU 12
#define ERROR_CODE_CONFIG_ASSERT_FAILED 13
#define ERROR_CODE_SDCARD_MOUNT_FAILED 21
#define ERROR_CODE_SDCARD_LOGGING_INIT_FAILED 22
#define ERROR_CODE_SDCARD_MKFS_FAILED 23

#define ERROR_CODE_FLASH_SECTOR_BACKUP_INCORRECT 51
#define ERROR_CODE_FLASH_SECTOR_RESTORE_INCORRECT 52

#endif /* ERROR_CODES_H_ */
