/*
 * error_codes.h
 *
 *  Created on: Oct 19, 2014
 *      Author: Max Zhao
 */

#ifndef ERROR_CODES_H_
#define ERROR_CODES_H_

#define ERROR_CODE_UNKNOWN_ERROR 0
#define ERROR_CODE_DEBUG_UART_FAILED 90
#define ERROR_CODE_DEBUG_UART_FAILED_SEND 91
#define ERROR_CODE_DEBUG_UART_NOT_READY_FOR_CRITICAL 92
#define ERROR_CODE_DEBUG_UART_FAILED_SEND_CRITICAL 93
#define ERROR_CODE_STACK_OVERFLOW 10
#define ERROR_CODE_MALLOC_FAILURE 11
#define ERROR_CODE_MAIN_SCHEDULER_FALL_THRU 12

#endif /* ERROR_CODES_H_ */
