function Tbr = T_base2rocket(pitch, yaw, roll)

Tbr = [ ...
    cosd(pitch)*cosd(roll) sind(yaw)*sind(pitch)*cosd(roll)-cosd(yaw)*sind(roll) sind(yaw)*sind(roll)+cosd(yaw)*sind(pitch)*cosd(roll); ...
    cosd(pitch)*sind(roll) cosd(yaw)*cosd(roll)+sind(yaw)*sind(pitch)*sind(roll) cosd(yaw)*sind(pitch)*sind(roll)-sind(yaw)*cosd(roll); ...
    -sind(pitch) sind(yaw)*cosd(pitch) cosd(yaw)*cosd(pitch) ...
    ];

end
