function Trb = T_rocket2base(pitch, yaw, roll)

Trb = [ ...
    cosd(pitch)*cosd(roll) cosd(pitch)*sind(roll) -sind(pitch); ...
    sind(yaw)*sind(pitch)*cosd(roll)-cosd(yaw)*sind(roll) cosd(yaw)*cosd(roll)+sind(yaw)*sind(pitch)*sind(roll) sind(yaw)*cosd(pitch); ...
    sind(yaw)*sind(roll)+cosd(yaw)*sind(pitch)*cosd(roll) cosd(yaw)*sind(pitch)*sind(roll)-sind(yaw)*cosd(roll) cosd(yaw)*cosd(pitch) ...
    ];

end
